### ISSUE TITLE
Some items' pages are not displayed due to an error

### ISSUE THREAD

**Issue by lipowskm** [kokarn/tarkov-tools#54]
Have a look at:
https://tarkov-tools.com/item/lab-violet-keycard
or
https://tarkov-tools.com/item/object-11sr-keycard

Going to those results in `TypeError: h is undefined`
Are you aware of this?

**Comment by kokarn** [comment]
It comes from this code `if(level > levelFilter.value){` so it's something from the PR you made. Lemme have a look

**Comment by lipowskm** [comment]
@kokarn 
It needs to be changed to
`if(levelFilter && level > levelFilter.value){
                return false;
            }`

But I wonder why this is affecting items page directly :/

**Comment by kokarn** [comment]
It's because the items page doesn't specify `levelFilter`
https://github.com/kokarn/tarkov-tools/blob/master/src/pages/item/index.js#L180-L182

Which results in `levelFilter` being undefined and the code crashing.

Fixed here https://github.com/kokarn/tarkov-tools/commit/594cd438d2118260f378418f869d03f5a333f3c2

**Comment by kokarn** [comment]
No worries, I should've checked anyway :)
